version: '3'

services:
  go-phone-otp-service:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis-db
  redis-db:
    build: db/redis
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis/data:/data
